# Generated by Django 5.1.6 on 2025-02-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
