# Generated by Django 5.1.6 on 2025-02-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_skill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(default='skill-logo.png', null=True, upload_to=''),
        ),
    ]
